#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=00:15:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node 
#SBATCH --mem=1G   # maximum memory per node
#SBATCH --partition=class-short    # class node(s)
#SBATCH --job-name="myjob"

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
./main.exe 2 64 > output2.txt
./main.exe 4 128 > output4.txt
./main.exe 6 256 > output6.txt
./main.exe 12 512 > output8.txt
./main.exe 16 1024 > output10.txt 
./main.exe 32 2048 > output12.txt 
